main: main.cpp ../../src/ray/ray.cpp ../../src/colour/colour.cpp ../../src/hitable/hitable.cpp ../../src/camera/camera.cpp ../../src/sphere/sphere.cpp ../../src/ray_tracing_utility/ray_tracing_utility.cpp ../../src/hitable_list/hitable_list.cpp ../../src/vector_3d/vector_3d.cpp
	g++ -Wall -std=c++17 main.cpp ../../src/ray/ray.cpp ../../src/colour/colour.cpp ../../src/hitable/hitable.cpp ../../src/camera/camera.cpp ../../src/sphere/sphere.cpp ../../src/ray_tracing_utility/ray_tracing_utility.cpp ../../src/hitable_list/hitable_list.cpp ../../src/vector_3d/vector_3d.cpp -o main.exe

clear:
	del main.exe