main: main.cpp \
	../../src/ray/ray.cpp \
	../../src/hitable/hitable.cpp \
	../../src/colour/colour.cpp \
	../../src/lambertian/lambertian.cpp \
	../../src/metal/metal.cpp \
	../../src/dielectric/dielectric.cpp \
	../../src/ray_tracing_utility/ray_tracing_utility.cpp \
	../../src/camera/camera.cpp \
	../../src/sphere/sphere.cpp \
	../../src/moving_sphere/moving_sphere.cpp \
	../../src/hitable_list/hitable_list.cpp \
	../../src/vector_3d/vector_3d.cpp \
	../../src/aabb/aabb.cpp \
	../../src/bvh/bvh.cpp

	g++ -Wall -std=c++17 \
	main.cpp \
	../../src/ray/ray.cpp \
	../../src/hitable/hitable.cpp \
	../../src/colour/colour.cpp \
	../../src/lambertian/lambertian.cpp \
	../../src/metal/metal.cpp \
	../../src/dielectric/dielectric.cpp \
	../../src/ray_tracing_utility/ray_tracing_utility.cpp \
	../../src/camera/camera.cpp \
	../../src/sphere/sphere.cpp \
	../../src/moving_sphere/moving_sphere.cpp \
	../../src/hitable_list/hitable_list.cpp \
	../../src/vector_3d/vector_3d.cpp \
	../../src/aabb/aabb.cpp \
	../../src/bvh/bvh.cpp \
	-o main.exe

clear:
	del main.exe