main: main.cpp ../../src/ray/ray.cpp ../../src/vector_3d/vector_3d.cpp ../../src/colour/colour.hpp
	g++ -Wall -std=c++17 main.cpp ../../src/ray/ray.cpp ../../src/vector_3d/vector_3d.cpp ../../src/colour/colour.hpp -o main.exe

clear:
	del main.exe